---
name: CAD-Calc
version: 0.26
author: []
abstract: generic cad-related geometry calculations
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::BigFloat: 0
  Math::Complex: 0
  Math::Round::Var: 0.02
  Math::Vec: 0.03
  Test::More: 0
recommends:
  Math::Geometry::Planar::Offset: 1.0301
provides:
  CAD::Calc:
    file: lib/CAD/Calc.pm
    version: 0.26
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
