---
name: CAD-Calc
version: 0.25
author:
  - Eric L. Wilhelm <ewilhelm at cpan dot org>
abstract: generic cad-related geometry calculations
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::BigFloat: 0
  Math::Complex: 0
  Math::Round::Var: 0.02
  Math::Vec: 0.03
  Test::More: 0
provides:
  CAD::Calc:
    file: lib/CAD/Calc.pm
    version: 0.25
generated_by: Module::Build version 0.2703
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
