---
name: CAD-Calc
version: 0.27
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: generic cad-related geometry calculations
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CAD-Calc
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/CAD-Calc/trunk
requires:
  Math::BigFloat: 0
  Math::Complex: 0
  Math::Round::Var: 0.02
  Math::Vec: 0.03
  Test::More: 0
recommends:
  Math::Geometry::Planar::Offset: 1.0301
provides:
  CAD::Calc:
    file: lib/CAD/Calc.pm
    version: 0.27
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
